package mx.syncro.chispazo;
import java.util.*;
public class Analyzer {
    public static class Stat { public final String key; public final double score; public final int count; Stat(String k,double s,int c){key=k;score=s;count=c;} }
    public static class Pick { public final int[] n; public final double score; public final String why; Pick(int[]n,double s,String w){this.n=n;score=s;why=w;} public String nums(){return String.format(Locale.US,"%02d %02d %02d %02d %02d",n[0],n[1],n[2],n[3],n[4]);}}
    private final List<Draw> ds; private final int[] freq=new int[29], f30=new int[29], f100=new int[29], gap=new int[29]; private final Map<String,Integer> pairs=new HashMap<>(), trios=new HashMap<>(); private double meanSum=72, sdSum=15;
    public Analyzer(List<Draw>d){ds=d; calc();}
    void calc(){Arrays.fill(gap,9999); ArrayList<Integer>sums=new ArrayList<>(); for(int i=0;i<ds.size();i++){Draw d=ds.get(i); int sum=0; for(int x:d.n){freq[x]++; if(i<30)f30[x]++; if(i<100)f100[x]++; if(gap[x]==9999)gap[x]=i; sum+=x;} sums.add(sum); for(int a=0;a<5;a++)for(int b=a+1;b<5;b++)pairs.merge(k2(d.n[a],d.n[b]),1,Integer::sum); for(int a=0;a<5;a++)for(int b=a+1;b<5;b++)for(int c=b+1;c<5;c++)trios.merge(k3(d.n[a],d.n[b],d.n[c]),1,Integer::sum);} if(!sums.isEmpty()){meanSum=sums.stream().mapToInt(x->x).average().orElse(72); double v=0;for(int x:sums)v+=(x-meanSum)*(x-meanSum);sdSum=Math.sqrt(v/sums.size());}}
    String k2(int a,int b){return a+"-"+b;} String k3(int a,int b,int c){return a+"-"+b+"-"+c;}
    public List<Stat> numbers(){ArrayList<Stat>o=new ArrayList<>(); for(int n=1;n<=28;n++){double z=.45*norm(freq[n],ds.size())+.35*norm(f100[n],Math.min(100,ds.size()))+.20*norm(f30[n],Math.min(30,ds.size()));o.add(new Stat(String.format(Locale.US,"%02d",n),z,freq[n]));}o.sort((a,b)->Double.compare(b.score,a.score));return o;}
    double norm(int c,int draws){ return draws==0?0:(c/(double)draws)/(5.0/28.0); }
    public List<Stat> topPairs(){return topMap(pairs);} public List<Stat> topTrios(){return topMap(trios);} List<Stat>topMap(Map<String,Integer>m){ArrayList<Stat>o=new ArrayList<>();for(Map.Entry<String,Integer>e:m.entrySet())o.add(new Stat(e.getKey(),e.getValue(),e.getValue()));o.sort((a,b)->Integer.compare(b.count,a.count));return o;}
    public List<Pick> generate(int howMany){ PriorityQueue<Pick> pq=new PriorityQueue<>((a,b)->Double.compare(a.score,b.score)); for(int a=1;a<=24;a++)for(int b=a+1;b<=25;b++)for(int c=b+1;c<=26;c++)for(int d=c+1;d<=27;d++)for(int e=d+1;e<=28;e++){int[]x={a,b,c,d,e};double s=score(x);String why=why(x);Pick p=new Pick(x,s,why);if(pq.size()<howMany)pq.add(p);else if(s>pq.peek().score){pq.poll();pq.add(p);}} ArrayList<Pick>o=new ArrayList<>(pq);o.sort((x,y)->Double.compare(y.score,x.score));return diversify(o); }
    double score(int[]x){double s=0;for(int n:x){s+=.38*norm(freq[n],ds.size())+.32*norm(f100[n],Math.min(100,ds.size()))+.20*norm(f30[n],Math.min(30,ds.size())); double g=Math.min(gap[n],30)/30.0;s+=.10*g;}for(int i=0;i<5;i++)for(int j=i+1;j<5;j++)s+=.08*pairs.getOrDefault(k2(x[i],x[j]),0);for(int i=0;i<5;i++)for(int j=i+1;j<5;j++)for(int k=j+1;k<5;k++)s+=.12*trios.getOrDefault(k3(x[i],x[j],x[k]),0);int even=0,sum=0;for(int n:x){if(n%2==0)even++;sum+=n;}if(even==2||even==3)s+=.8;else s-=.5; s-=Math.abs(sum-meanSum)/Math.max(8,sdSum)*.25; int span=x[4]-x[0];if(span>=18)s+=.25; if(recentOverlap(x)>=4)s-=1.5; return s;}
    int recentOverlap(int[]x){int mx=0;for(int i=0;i<Math.min(20,ds.size());i++){int c=0;for(int a:x)for(int b:ds.get(i).n)if(a==b)c++;mx=Math.max(mx,c);}return mx;}
    String why(int[]x){int sum=0,ev=0;for(int n:x){sum+=n;if(n%2==0)ev++;}int pc=0,tc=0;for(int i=0;i<5;i++)for(int j=i+1;j<5;j++)pc+=pairs.getOrDefault(k2(x[i],x[j]),0);for(int i=0;i<5;i++)for(int j=i+1;j<5;j++)for(int k=j+1;k<5;k++)tc+=trios.getOrDefault(k3(x[i],x[j],x[k]),0);return "par/impar "+ev+"/"+(5-ev)+" · suma "+sum+" · fuerza pares "+pc+" · fuerza tríos "+tc;}
    List<Pick>diversify(List<Pick>in){ArrayList<Pick>o=new ArrayList<>();for(Pick p:in){boolean ok=true;for(Pick q:o)if(overlap(p.n,q.n)>=4){ok=false;break;}if(ok)o.add(p);if(o.size()>=10)break;}return o;}int overlap(int[]a,int[]b){int c=0;for(int x:a)for(int y:b)if(x==y)c++;return c;}
    public double meanSum(){return meanSum;}
}
