plugins {
    id 'com.android.application'
}

android {
    namespace 'com.syncro.inescanner'
    compileSdk 35

    defaultConfig {
        applicationId 'com.syncro.inescanner'
        minSdk 29
        targetSdk 35
        versionCode 4
        versionName '0.4.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'com.google.mlkit:text-recognition:16.0.1'
}
