package mx.consultamx.fraude;

import android.app.*;
import android.os.Bundle;
import android.content.*;
import android.database.Cursor;
import android.database.sqlite.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import java.security.MessageDigest;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    static final int NAVY=Color.rgb(11,19,36), TEAL=Color.rgb(15,118,110), BG=Color.rgb(248,250,252), MUTED=Color.rgb(100,116,139), RED=Color.rgb(185,28,28), AMBER=Color.rgb(180,83,9), GREEN=Color.rgb(21,128,61), BLUE=Color.rgb(29,78,216);
    static final String RENAPO="https://www.gob.mx/curp/";
    static final String CEDULA="https://www.gob.mx/cedulaprofesional";
    static final String SAT69="https://www.sat.gob.mx/minisitio/DatosAbiertos/contribuyentes_publicados.html";
    static final String RSPS="https://rsps.gob.mx/";
    DB db; String user=""; LinearLayout root,body; TextView balanceText;

    int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} 
    GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    TextView tv(String s,int sp,int c,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);if(bold)v.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);return v;}
    EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(16);e.setPadding(dp(16),dp(12),dp(16),dp(12));e.setBackground(bg(Color.WHITE,14));return e;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(15);b.setAllCaps(false);b.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);b.setBackground(bg(TEAL,14));return b;}
    void add(LinearLayout p,View v,int h){LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,h<0?h:dp(h));lp.setMargins(0,dp(6),0,dp(6));p.addView(v,lp);} 
    LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(18),dp(18),dp(18));c.setBackground(bg(Color.WHITE,18));return c;}
    String fmt(double x){return String.format(Locale.US,"%.2f",x);} void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new DB(this);getWindow().setStatusBarColor(NAVY);showAuth();}

    void base(String title,boolean nav){ScrollView sc=new ScrollView(this);sc.setFillViewport(true);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(28));root.setBackgroundColor(BG);sc.addView(root);setContentView(sc);LinearLayout h=card();h.addView(tv("CONSULTA MX",13,TEAL,true));h.addView(tv(title,27,NAVY,true));if(nav){balanceText=tv("Saldo: $"+fmt(db.balance(user)),16,NAVY,true);h.addView(balanceText);}add(root,h,-2);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);root.addView(body,new LinearLayout.LayoutParams(-1,-2));}

    void showAuth(){base("Verificación pública por consulta",false);LinearLayout c=card();c.addView(tv("ConsultaMX v2",20,NAVY,true));c.addView(tv("CURP, fuentes oficiales y señales comunitarias. Cada consulta cuesta $1.",14,MUTED,false));EditText email=input("Correo");EditText pass=input("Contraseña");pass.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);add(c,email,52);add(c,pass,52);Button login=btn("Entrar");Button reg=btn("Crear cuenta");reg.setBackground(bg(NAVY,14));add(c,login,52);add(c,reg,52);body.addView(c);login.setOnClickListener(v->{String e=email.getText().toString().trim().toLowerCase();if(db.login(e,pass.getText().toString())){user=e;showHome();}else toast("Correo o contraseña incorrectos");});reg.setOnClickListener(v->{String e=email.getText().toString().trim().toLowerCase();if(!e.contains("@")||pass.length()<4){toast("Correo válido y contraseña de 4+ caracteres");return;}if(db.register(e,pass.getText().toString())){user=e;showHome();}else toast("Ese correo ya existe");});}

    void showHome(){base("¿Qué quieres consultar?",true);LinearLayout c=card();c.addView(tv("Expediente de persona",19,NAVY,true));c.addView(tv("Primero revisa la caché local. Si no existe o está vencida, abre la fuente oficial para verificar y actualizar.",13,MUTED,false));Button person=btn("Consultar CURP por $1");add(c,person,54);Button signal=btn("Consultar teléfono / CLABE / correo / URL");signal.setBackground(bg(NAVY,14));add(c,signal,54);body.addView(c);person.setOnClickListener(v->showPersonQuery());signal.setOnClickListener(v->showSignalQuery());
      LinearLayout a=card();a.addView(tv("Cuenta",18,NAVY,true));Button wallet=btn("Recargar saldo demo");Button hist=btn("Historial");Button sources=btn("Fuentes oficiales incluidas");Button out=btn("Cerrar sesión");wallet.setBackground(bg(BLUE,14));hist.setBackground(bg(Color.rgb(51,65,85),14));sources.setBackground(bg(TEAL,14));out.setBackground(bg(Color.rgb(71,85,105),14));add(a,wallet,48);add(a,hist,48);add(a,sources,48);add(a,out,48);body.addView(a);wallet.setOnClickListener(v->showWallet());hist.setOnClickListener(v->showHistory());sources.setOnClickListener(v->showSources());out.setOnClickListener(v->{user="";showAuth();});}

    void showPersonQuery(){base("Consulta de persona",true);LinearLayout c=card();c.addView(tv("CURP",18,NAVY,true));EditText curp=input("18 caracteres");curp.setAllCaps(true);EditText rfc=input("RFC opcional para listas SAT");rfc.setAllCaps(true);add(c,curp,56);add(c,rfc,56);Button go=btn("Consultar por $1.00");Button back=btn("Volver");back.setBackground(bg(NAVY,14));add(c,go,54);add(c,back,48);body.addView(c);back.setOnClickListener(v->showHome());go.setOnClickListener(v->{String x=curp.getText().toString().trim().toUpperCase(Locale.ROOT);String rr=rfc.getText().toString().trim().toUpperCase(Locale.ROOT);if(!validCurp(x)){toast("CURP inválida: deben ser 18 caracteres con estructura válida");return;}if(db.balance(user)<1){toast("Saldo insuficiente");showWallet();return;}Cursor cached=db.getCurp(x);boolean hit=cached.moveToFirst();String status=hit?cached.getString(1):"SIN_VERIFICAR";String checked=hit?cached.getString(2):"";cached.close();long q=db.chargePersonQuery(user,x,rr,hit?"CACHE":"FUENTE_OFICIAL_REQUERIDA");if(q<0){toast("No se pudo cobrar la consulta");return;}showPersonResult(x,rr,status,checked,hit,q);});}

    boolean validCurp(String s){return s.matches("^[A-Z][AEIOUX][A-Z]{2}\\d{6}[HM][A-Z]{5}[A-Z0-9]\\d$");}

    void showPersonResult(String curp,String rfc,String status,String checked,boolean cacheHit,long qid){base("Resultado CURP",true);LinearLayout c=card();c.addView(tv(cacheHit?"CACHÉ LOCAL ENCONTRADA":"REQUIERE VERIFICACIÓN OFICIAL",18,cacheHit?GREEN:AMBER,true));c.addView(tv("CURP: "+mask(curp),14,NAVY,true));c.addView(tv("Origen de esta respuesta: "+(cacheHit?"base local":"sin registro local"),13,MUTED,false));if(cacheHit)c.addView(tv("Estado guardado: "+status+" · verificado: "+checked,13,MUTED,false));c.addView(tv("Folio Q-"+qid+" · cargo $1.00",12,MUTED,false));body.addView(c);
      LinearLayout s=card();s.addView(tv("Verificación oficial",18,NAVY,true));s.addView(tv("El portal público de RENAPO puede requerir interacción humana. ConsultaMX prellena la CURP cuando el sitio lo permite, pero no evade códigos de verificación ni accesos restringidos.",13,MUTED,false));Button renapo=btn("Abrir RENAPO con CURP prellenada");Button save=btn("Marcar como verificada y guardar caché");save.setBackground(bg(GREEN,14));Button ced=btn("Consultar cédula profesional SEP");ced.setBackground(bg(BLUE,14));add(s,renapo,52);add(s,save,52);add(s,ced,52);if(rfc.length()>=12){Button sat=btn("Consultar SAT 69 / 69-B");sat.setBackground(bg(AMBER,14));add(s,sat,52);sat.setOnClickListener(v->openOfficial(SAT69,""));}Button rsps=btn("Consultar servidores públicos sancionados");rsps.setBackground(bg(Color.rgb(127,29,29),14));add(s,rsps,52);Button back=btn("Inicio");back.setBackground(bg(NAVY,14));add(s,back,48);body.addView(s);renapo.setOnClickListener(v->openOfficial(RENAPO,curp));ced.setOnClickListener(v->openOfficial(CEDULA,curp));rsps.setOnClickListener(v->openOfficial(RSPS,""));save.setOnClickListener(v->{db.saveCurp(curp,"VERIFICADA_POR_USUARIO",now());toast("CURP guardada en caché local");showPersonResult(curp,rfc,"VERIFICADA_POR_USUARIO",now(),true,qid);});back.setOnClickListener(v->showHome());}

    void openOfficial(String url,String curp){Intent i=new Intent(this,OfficialWebActivity.class);i.putExtra("url",url);i.putExtra("curp",curp);startActivity(i);}

    void showSignalQuery(){base("Consulta de señal",true);LinearLayout c=card();EditText value=input("Teléfono, CLABE, correo o URL");add(c,value,58);Button go=btn("Consultar por $1.00");Button back=btn("Volver");back.setBackground(bg(NAVY,14));add(c,go,54);add(c,back,48);body.addView(c);back.setOnClickListener(v->showHome());go.setOnClickListener(v->{String x=value.getText().toString().trim();if(x.length()<4){toast("Captura un dato válido");return;}if(db.balance(user)<1){toast("Saldo insuficiente");showWallet();return;}String type=detect(x);int reports=db.countReports(type,x);int risk=Math.min(100,reports*25);long id=db.chargeSignal(user,type,x,risk);showSignalResult(type,x,reports,risk,id);});}
    String detect(String x){String s=x.trim();if(s.contains("@"))return "CORREO";if(s.startsWith("http://")||s.startsWith("https://")||s.contains("www."))return "URL";String d=s.replaceAll("\\D","");if(d.length()==18)return "CLABE";if(d.length()>=10&&d.length()<=13)return "TELÉFONO";return "DATO";}
    void showSignalResult(String type,String x,int reports,int risk,long id){base("Resultado de señal",true);LinearLayout c=card();int color=risk>=70?RED:risk>=35?AMBER:GREEN;c.addView(tv((risk>=70?"RIESGO ALTO":risk>=35?"RIESGO MEDIO":"SIN ALERTAS LOCALES")+" · "+risk+"/100",20,color,true));c.addView(tv(type+": "+mask(x),14,NAVY,true));c.addView(tv("Reportes locales coincidentes: "+reports,14,MUTED,false));c.addView(tv("Sin coincidencias no significa que la operación sea segura.",13,MUTED,false));c.addView(tv("Folio Q-"+id+" · cargo $1.00",12,MUTED,false));Button home=btn("Inicio");add(c,home,48);home.setOnClickListener(v->showHome());body.addView(c);}

    void showSources(){base("Fuentes oficiales",true);LinearLayout c=card();c.addView(tv("RENAPO / gob.mx CURP",17,NAVY,true));c.addView(tv("Consulta pública de CURP. Se usa como fuente primaria de identidad.",13,MUTED,false));c.addView(tv("SEP · Registro Nacional de Profesionistas",17,NAVY,true));c.addView(tv("Consulta pública de cédula profesional.",13,MUTED,false));c.addView(tv("SAT · Artículos 69 y 69-B",17,NAVY,true));c.addView(tv("Listados públicos de contribuyentes. Requieren RFC para una coincidencia confiable.",13,MUTED,false));c.addView(tv("Registro de servidores públicos sancionados",17,NAVY,true));c.addView(tv("Fuente oficial separada de los reportes comunitarios.",13,MUTED,false));c.addView(tv("Importante",17,AMBER,true));c.addView(tv("ConsultaMX no debe presentar una ausencia de coincidencias como certificación de que una persona es segura o que no ha cometido fraude.",13,MUTED,false));Button b=btn("Volver");add(c,b,48);b.setOnClickListener(v->showHome());body.addView(c);}

    void showWallet(){base("Monedero",true);LinearLayout c=card();c.addView(tv("Saldo $"+fmt(db.balance(user)),32,NAVY,true));c.addView(tv("Recargas de DEMOSTRACIÓN. Para dinero real hace falta backend y confirmación del proveedor de pago.",13,AMBER,true));for(int a:new int[]{20,50,100}){Button b=btn("Acreditar $"+a+" demo");add(c,b,48);b.setOnClickListener(v->{db.credit(user,a,"RECARGA_DEMO");showWallet();});}Button back=btn("Volver");back.setBackground(bg(NAVY,14));add(c,back,48);back.setOnClickListener(v->showHome());body.addView(c);}

    void showHistory(){base("Historial",true);LinearLayout c=card();Cursor q=db.history(user);if(!q.moveToFirst())c.addView(tv("Sin consultas.",14,MUTED,false));else do{TextView t=tv("Q-"+q.getLong(0)+" · "+q.getString(1)+"\n"+mask(q.getString(2))+" · "+q.getString(3)+"\n"+q.getString(4),14,NAVY,false);t.setPadding(0,dp(9),0,dp(9));c.addView(t);}while(q.moveToNext());q.close();Button b=btn("Volver");add(c,b,48);b.setOnClickListener(v->showHome());body.addView(c);}

    String mask(String x){if(x==null)return "";if(x.length()<8)return x;return x.substring(0,4)+"••••"+x.substring(x.length()-3);}
    static String hash(String s){try{MessageDigest md=MessageDigest.getInstance("SHA-256");byte[] b=md.digest(s.getBytes());StringBuilder x=new StringBuilder();for(byte q:b)x.append(String.format("%02x",q));return x.toString();}catch(Exception e){return s;}}
    static String now(){return new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.getDefault()).format(new Date());}

    static class DB extends SQLiteOpenHelper{
        DB(Context c){super(c,"consultamx.db",null,2);} 
        public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE users(email TEXT PRIMARY KEY,pass TEXT NOT NULL,created TEXT NOT NULL)");d.execSQL("CREATE TABLE wallet(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT,amount REAL,concept TEXT,created TEXT)");d.execSQL("CREATE TABLE queries(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT,type TEXT,value TEXT,detail TEXT,cost REAL,created TEXT)");d.execSQL("CREATE TABLE reports(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT,type TEXT,value TEXT,note TEXT,created TEXT)");d.execSQL("CREATE TABLE curp_cache(curp TEXT PRIMARY KEY,status TEXT,checked TEXT)");}
        public void onUpgrade(SQLiteDatabase d,int oldV,int newV){if(oldV<2){try{d.execSQL("ALTER TABLE queries ADD COLUMN detail TEXT DEFAULT ''");}catch(Exception ignored){}try{d.execSQL("CREATE TABLE IF NOT EXISTS curp_cache(curp TEXT PRIMARY KEY,status TEXT,checked TEXT)");}catch(Exception ignored){}}}
        boolean register(String e,String p){try{ContentValues v=new ContentValues();v.put("email",e);v.put("pass",hash(p));v.put("created",now());return getWritableDatabase().insertOrThrow("users",null,v)>0;}catch(Exception x){return false;}}
        boolean login(String e,String p){Cursor c=getReadableDatabase().rawQuery("SELECT 1 FROM users WHERE email=? AND pass=?",new String[]{e,hash(p)});boolean ok=c.moveToFirst();c.close();return ok;}
        double balance(String e){Cursor c=getReadableDatabase().rawQuery("SELECT COALESCE(SUM(amount),0) FROM wallet WHERE email=?",new String[]{e});double v=c.moveToFirst()?c.getDouble(0):0;c.close();return v;}
        void credit(String e,double a,String concept){ContentValues v=new ContentValues();v.put("email",e);v.put("amount",a);v.put("concept",concept);v.put("created",now());getWritableDatabase().insert("wallet",null,v);}
        long chargePersonQuery(String e,String curp,String rfc,String detail){return charge(e,"CURP",curp,detail+(rfc.length()>0?" RFC:"+rfc:""));}
        long chargeSignal(String e,String type,String value,int risk){return charge(e,type,value,"RIESGO_LOCAL:"+risk);}
        long charge(String e,String type,String value,String detail){SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{Cursor c=d.rawQuery("SELECT COALESCE(SUM(amount),0) FROM wallet WHERE email=?",new String[]{e});double bal=c.moveToFirst()?c.getDouble(0):0;c.close();if(bal<1)return -1;ContentValues w=new ContentValues();w.put("email",e);w.put("amount",-1.0);w.put("concept","CONSULTA_"+type);w.put("created",now());d.insertOrThrow("wallet",null,w);ContentValues q=new ContentValues();q.put("email",e);q.put("type",type);q.put("value",value);q.put("detail",detail);q.put("cost",1.0);q.put("created",now());long id=d.insertOrThrow("queries",null,q);d.setTransactionSuccessful();return id;}catch(Exception ex){return -1;}finally{d.endTransaction();}}
        Cursor getCurp(String c){return getReadableDatabase().rawQuery("SELECT curp,status,checked FROM curp_cache WHERE curp=?",new String[]{c});}
        void saveCurp(String c,String status,String checked){ContentValues v=new ContentValues();v.put("curp",c);v.put("status",status);v.put("checked",checked);getWritableDatabase().insertWithOnConflict("curp_cache",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
        int countReports(String type,String value){Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*) FROM reports WHERE type=? AND lower(value)=lower(?)",new String[]{type,value});int n=c.moveToFirst()?c.getInt(0):0;c.close();return n;}
        Cursor history(String e){return getReadableDatabase().rawQuery("SELECT id,type,value,detail,created FROM queries WHERE email=? ORDER BY id DESC LIMIT 100",new String[]{e});}
    }
}
