package mx.consultamx.fraude;

import android.app.*;
import android.os.Bundle;
import android.content.*;
import android.database.Cursor;
import android.database.sqlite.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import java.security.MessageDigest;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    static final int NAVY=Color.rgb(11,19,36), TEAL=Color.rgb(15,118,110), BG=Color.rgb(248,250,252), MUTED=Color.rgb(100,116,139), RED=Color.rgb(185,28,28), AMBER=Color.rgb(180,83,9), GREEN=Color.rgb(21,128,61);
    DB db; String user=""; LinearLayout root, body; TextView balanceText;
    int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    TextView tv(String s,int sp,int c,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
    EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(16);e.setPadding(dp(16),dp(12),dp(16),dp(12));e.setBackground(bg(Color.WHITE,14));return e;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(15);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(bg(TEAL,14));return b;}
    void add(LinearLayout p,View v,int h){LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,h<0?h:dp(h));lp.setMargins(0,dp(6),0,dp(6));p.addView(v,lp);} 
    LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(18),dp(18),dp(18));c.setBackground(bg(Color.WHITE,18));return c;}
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new DB(this);getWindow().setStatusBarColor(NAVY);showAuth();}

    void base(String title, boolean nav){ScrollView sc=new ScrollView(this);sc.setFillViewport(true);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(24));root.setBackgroundColor(BG);sc.addView(root);setContentView(sc);LinearLayout head=card();TextView brand=tv("CONSULTA MX",13,TEAL,true);head.addView(brand);TextView t=tv(title,27,NAVY,true);head.addView(t);if(nav){balanceText=tv("Saldo: $"+fmt(db.balance(user)),16,NAVY,true);head.addView(balanceText);}add(root,head,-2);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);root.addView(body,new LinearLayout.LayoutParams(-1,-2));}
    String fmt(double x){return String.format(Locale.US,"%.2f",x);} void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}

    void showAuth(){base("Verifica antes de pagar",false);LinearLayout c=card();c.addView(tv("Consulta señales de riesgo por $1",18,NAVY,true));TextView sub=tv("Teléfono, CLABE, correo o URL. Crea tu cuenta para comenzar.",14,MUTED,false);sub.setPadding(0,dp(6),0,dp(10));c.addView(sub);EditText email=input("Correo");EditText pass=input("Contraseña");pass.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);add(c,email,52);add(c,pass,52);Button login=btn("Entrar");add(c,login,52);Button reg=btn("Crear cuenta");reg.setBackground(bg(NAVY,14));add(c,reg,52);body.addView(c);login.setOnClickListener(v->{String e=email.getText().toString().trim().toLowerCase();if(db.login(e,pass.getText().toString())){user=e;showHome();}else toast("Correo o contraseña incorrectos");});reg.setOnClickListener(v->{String e=email.getText().toString().trim().toLowerCase();if(!e.contains("@")||pass.length()<4){toast("Captura un correo válido y contraseña de 4+ caracteres");return;}if(db.register(e,pass.getText().toString())){user=e;toast("Cuenta creada. Saldo inicial $0.00");showHome();}else toast("Ese correo ya existe");});}

    void showHome(){base("¿Qué quieres verificar?",true);LinearLayout hero=card();hero.addView(tv("Cada consulta cuesta $1.00",16,NAVY,true));hero.addView(tv("Tu saldo se descuenta sólo cuando se genera un resultado.",13,MUTED,false));Button q=btn("Nueva consulta");add(hero,q,54);body.addView(hero);q.setOnClickListener(v->showQuery());
      LinearLayout actions=card();TextView a=tv("Acciones",18,NAVY,true);actions.addView(a);Button wallet=btn("Recargar saldo");Button hist=btn("Historial de consultas");Button report=btn("Reportar señal de fraude");Button out=btn("Cerrar sesión");wallet.setBackground(bg(NAVY,14));hist.setBackground(bg(Color.rgb(51,65,85),14));report.setBackground(bg(AMBER,14));out.setBackground(bg(Color.rgb(71,85,105),14));add(actions,wallet,50);add(actions,hist,50);add(actions,report,50);add(actions,out,50);body.addView(actions);wallet.setOnClickListener(v->showWallet());hist.setOnClickListener(v->showHistory());report.setOnClickListener(v->showReport());out.setOnClickListener(v->{user="";showAuth();});
      LinearLayout note=card();note.addView(tv("Importante",16,NAVY,true));note.addView(tv("Esta versión instala y funciona localmente. Las recargas son de demostración y las señales se consultan en la base local del teléfono. Para venta pública se debe conectar el monedero y la base comunitaria a un backend seguro.",13,MUTED,false));body.addView(note);}

    void showQuery(){base("Nueva consulta",true);LinearLayout c=card();c.addView(tv("Pega un dato",18,NAVY,true));c.addView(tv("Detectamos automáticamente si parece teléfono, CLABE, correo o URL.",13,MUTED,false));EditText value=input("Ej. 8112345678 / CLABE / correo / URL");add(c,value,58);Button go=btn("Consultar por $1.00");add(c,go,54);Button back=btn("Volver");back.setBackground(bg(NAVY,14));add(c,back,48);body.addView(c);back.setOnClickListener(v->showHome());go.setOnClickListener(v->{String x=value.getText().toString().trim();if(x.length()<4){toast("Captura un dato válido");return;}if(db.balance(user)<1){toast("Saldo insuficiente. Recarga para consultar.");showWallet();return;}String type=detect(x);int reports=db.countReports(type,x);int risk=score(type,x,reports);String level=risk>=70?"ALTO":risk>=35?"MEDIO":"BAJO";long id=db.chargeAndQuery(user,type,x,risk,level);if(id<0){toast("No se pudo realizar la consulta");return;}showResult(type,x,risk,level,reports,id);});}
    String detect(String x){String s=x.trim();if(s.contains("@"))return "CORREO";if(s.startsWith("http://")||s.startsWith("https://")||s.contains("www."))return "URL";String d=s.replaceAll("\\D","");if(d.length()==18)return "CLABE";if(d.length()>=10&&d.length()<=13)return "TELÉFONO";return "DATO";}
    int score(String type,String x,int reports){int s=Math.min(80,reports*22);String z=x.toLowerCase();if(type.equals("URL")&&(z.contains("bit.ly")||z.contains("tinyurl")||z.contains("pago-seguro")))s+=20;if(type.equals("CORREO")&&(z.endsWith("@mailinator.com")||z.contains("premio")))s+=15;if(type.equals("TELÉFONO")&&x.replaceAll("\\D","").matches("(81|55|33)0000.*"))s+=15;return Math.min(100,s);}
    void showResult(String type,String x,int risk,String level,int reports,long id){base("Resultado de consulta",true);int color=level.equals("ALTO")?RED:level.equals("MEDIO")?AMBER:GREEN;LinearLayout c=card();TextView badge=tv(level+"  •  "+risk+"/100",22,color,true);c.addView(badge);c.addView(tv(type+": "+mask(x),14,NAVY,true));c.addView(tv("Coincidencias de reportes: "+reports,14,MUTED,false));String msg=reports>0?"Se encontraron señales reportadas en la base local. Verifica identidad, titularidad y operación antes de transferir.":"No hay reportes locales asociados a este dato. Esto NO garantiza que sea seguro; valida identidad y evita transferencias apresuradas.";TextView m=tv(msg,14,NAVY,false);m.setPadding(0,dp(12),0,dp(12));c.addView(m);c.addView(tv("Folio: Q-"+id+"  •  Cargo aplicado: $1.00",12,MUTED,false));Button rep=btn("Reportar este dato");rep.setBackground(bg(AMBER,14));add(c,rep,50);Button home=btn("Volver al inicio");add(c,home,50);body.addView(c);rep.setOnClickListener(v->showReportPrefill(type,x));home.setOnClickListener(v->showHome());}
    String mask(String x){if(x.length()<8)return x;return x.substring(0,Math.min(4,x.length()))+"••••"+x.substring(x.length()-Math.min(3,x.length()));}

    void showWallet(){base("Monedero",true);LinearLayout c=card();c.addView(tv("Saldo disponible",14,MUTED,false));c.addView(tv("$"+fmt(db.balance(user)),34,NAVY,true));c.addView(tv("Recarga de demostración",17,AMBER,true));c.addView(tv("Para probar el APK, estas recargas se acreditan localmente. En producción deben acreditarse sólo desde el servidor al confirmar el pago.",13,MUTED,false));for(int amt:new int[]{20,50,100,500}){Button b=btn("Acreditar $"+amt+" demo");add(c,b,48);b.setOnClickListener(v->{db.credit(user,amt,"RECARGA_DEMO");toast("Recarga demo acreditada");showWallet();});}Button h=btn("Ver movimientos");h.setBackground(bg(NAVY,14));add(c,h,48);Button back=btn("Volver");back.setBackground(bg(Color.rgb(71,85,105),14));add(c,back,48);body.addView(c);h.setOnClickListener(v->showMovements());back.setOnClickListener(v->showHome());}
    void showMovements(){base("Movimientos",true);LinearLayout c=card();Cursor cur=db.movements(user);if(!cur.moveToFirst())c.addView(tv("Sin movimientos todavía.",14,MUTED,false));else do{double a=cur.getDouble(1);String line=(a>=0?"+":"")+"$"+fmt(a)+"  "+cur.getString(2)+"\n"+cur.getString(3);TextView t=tv(line,14,a>=0?GREEN:NAVY,a>=0);t.setPadding(0,dp(9),0,dp(9));c.addView(t);}while(cur.moveToNext());cur.close();Button b=btn("Volver");add(c,b,48);b.setOnClickListener(v->showWallet());body.addView(c);}

    void showHistory(){base("Historial",true);LinearLayout c=card();Cursor cur=db.history(user);if(!cur.moveToFirst())c.addView(tv("Aún no has realizado consultas.",14,MUTED,false));else do{String line="#Q-"+cur.getLong(0)+"  "+cur.getString(1)+"  "+cur.getString(4)+"\n"+mask(cur.getString(2))+"  •  riesgo "+cur.getInt(3)+"/100\n"+cur.getString(5);TextView t=tv(line,14,NAVY,false);t.setPadding(0,dp(10),0,dp(10));c.addView(t);}while(cur.moveToNext());cur.close();Button b=btn("Volver");add(c,b,48);b.setOnClickListener(v->showHome());body.addView(c);}

    void showReport(){showReportPrefill("","");}
    void showReportPrefill(String preType,String preValue){base("Reportar señal",true);LinearLayout c=card();c.addView(tv("Ayuda a prevenir fraudes",18,NAVY,true));c.addView(tv("Reportar es gratis. No publiques contraseñas, NIP ni datos sensibles innecesarios.",13,MUTED,false));EditText value=input("Teléfono, CLABE, correo o URL");value.setText(preValue);EditText note=input("¿Qué ocurrió? Ej. pidió anticipo y dejó de responder");add(c,value,56);add(c,note,80);Button save=btn("Enviar reporte");save.setBackground(bg(AMBER,14));add(c,save,52);Button back=btn("Cancelar");back.setBackground(bg(NAVY,14));add(c,back,48);body.addView(c);save.setOnClickListener(v->{String x=value.getText().toString().trim();if(x.length()<4||note.length()<5){toast("Captura el dato y una descripción breve");return;}db.report(user,detect(x),x,note.getText().toString().trim());toast("Reporte guardado");showHome();});back.setOnClickListener(v->showHome());}

    static String hash(String s){try{MessageDigest md=MessageDigest.getInstance("SHA-256");byte[] b=md.digest(s.getBytes());StringBuilder x=new StringBuilder();for(byte q:b)x.append(String.format("%02x",q));return x.toString();}catch(Exception e){return s;}}
    static String now(){return new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.getDefault()).format(new Date());}

    static class DB extends SQLiteOpenHelper {
        DB(Context c){super(c,"consultamx.db",null,1);} public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE users(email TEXT PRIMARY KEY, pass TEXT NOT NULL, created TEXT NOT NULL)");d.execSQL("CREATE TABLE wallet(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT,amount REAL,concept TEXT,created TEXT)");d.execSQL("CREATE TABLE queries(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT,type TEXT,value TEXT,risk INTEGER,level TEXT,cost REAL,created TEXT)");d.execSQL("CREATE TABLE reports(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT,type TEXT,value TEXT,note TEXT,created TEXT)");seed(d);} public void onUpgrade(SQLiteDatabase d,int a,int b){}
        void seed(SQLiteDatabase d){ContentValues c=new ContentValues();c.put("email","system@local");c.put("type","TELÉFONO");c.put("value","5500001234");c.put("note","Señal de demostración: anticipo no entregado");c.put("created",now());d.insert("reports",null,c);ContentValues e=new ContentValues();e.put("email","system@local");e.put("type","CORREO");e.put("value","premio@mailinator.com");e.put("note","Señal de demostración: mensaje de premio falso");e.put("created",now());d.insert("reports",null,e);}
        boolean register(String e,String p){try{ContentValues v=new ContentValues();v.put("email",e);v.put("pass",hash(p));v.put("created",now());return getWritableDatabase().insertOrThrow("users",null,v)>0;}catch(Exception x){return false;}}
        boolean login(String e,String p){Cursor c=getReadableDatabase().rawQuery("SELECT 1 FROM users WHERE email=? AND pass=?",new String[]{e,hash(p)});boolean ok=c.moveToFirst();c.close();return ok;}
        double balance(String e){Cursor c=getReadableDatabase().rawQuery("SELECT COALESCE(SUM(amount),0) FROM wallet WHERE email=?",new String[]{e});double v=c.moveToFirst()?c.getDouble(0):0;c.close();return v;}
        void credit(String e,double a,String concept){ContentValues v=new ContentValues();v.put("email",e);v.put("amount",a);v.put("concept",concept);v.put("created",now());getWritableDatabase().insert("wallet",null,v);}
        long chargeAndQuery(String e,String type,String value,int risk,String level){SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{Cursor c=d.rawQuery("SELECT COALESCE(SUM(amount),0) FROM wallet WHERE email=?",new String[]{e});double bal=c.moveToFirst()?c.getDouble(0):0;c.close();if(bal<1)return -1;ContentValues q=new ContentValues();q.put("email",e);q.put("type",type);q.put("value",value);q.put("risk",risk);q.put("level",level);q.put("cost",1.0);q.put("created",now());long id=d.insertOrThrow("queries",null,q);ContentValues w=new ContentValues();w.put("email",e);w.put("amount",-1.0);w.put("concept","CONSULTA Q-"+id);w.put("created",now());d.insertOrThrow("wallet",null,w);d.setTransactionSuccessful();return id;}catch(Exception x){return -1;}finally{d.endTransaction();}}
        int countReports(String type,String value){Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*) FROM reports WHERE type=? AND lower(value)=lower(?)",new String[]{type,value});int n=c.moveToFirst()?c.getInt(0):0;c.close();return n;}
        void report(String e,String type,String value,String note){ContentValues v=new ContentValues();v.put("email",e);v.put("type",type);v.put("value",value);v.put("note",note);v.put("created",now());getWritableDatabase().insert("reports",null,v);}
        Cursor history(String e){return getReadableDatabase().rawQuery("SELECT id,type,value,risk,level,created FROM queries WHERE email=? ORDER BY id DESC LIMIT 100",new String[]{e});}
        Cursor movements(String e){return getReadableDatabase().rawQuery("SELECT id,amount,concept,created FROM wallet WHERE email=? ORDER BY id DESC LIMIT 100",new String[]{e});}
    }
}
